export const ANDROID_EXECUTION_CAPABILITY = 'ANDROID';
export const ANDROID_EXECUTION_RUNNER_KIND = 'MACOS_AGENT';
export const BROWSER_EXECUTION_CAPABILITY = 'BROWSER';
export const BROWSER_EXECUTION_RUNNER_KIND = 'CONTROL_PLANE';
